import{a as L,S,i as n}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const P="55724103-14f076f0e5cd96e081e15651b",C="https://pixabay.com/api/";async function u(r,t){const{data:a}=await L(C,{params:{per_page:15,page:t,key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}});return a}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),c=document.querySelector(".js-load-more");let v=new S(".gallery a",{captionsData:"alt",captionDelay:200});function h(r){const t=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:s,comments:b,downloads:w})=>`
    <li class="gallery-item">
    <a href="${i}"><img src="${a}" alt="${e}" class="gallery-image"/></a>
    <ul class="gallery-item-list">
    <li><p>Likes<br> <span>${o}</span></p></li>
    <li><p>Views<br> <span>${s}</span></p></li>
    <li><p>Comments<br> <span>${b}</span></p></li>
    <li><p>Downloads<br> <span>${w}</span></p></li>
    
    </ul>
    </li>
    `).join("");g.insertAdjacentHTML("beforeend",t),v.refresh()}function M(){g.innerHTML=""}function m(){p.classList.remove("is-hidden")}function f(){p.classList.add("is-hidden")}function q(){c.classList.remove("is-hidden")}function y(){c.classList.add("is-hidden")}const $=document.querySelector(".form");$.addEventListener("submit",O);let l=1,d="";c.addEventListener("click",R);async function O(r){if(r.preventDefault(),d=r.currentTarget.elements["search-text"].value.trim(),d===""){n.warning({position:"topRight",message:"Please fill out this field.",backgroundColor:"white"});return}l=1,M(),m(),y();try{const t=await u(d,l);t.hits.length===0?n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white"}):(h(t.hits),Math.ceil(t.totalHits/15)>=1&&q())}catch(t){console.log(t),n.error({position:"topRight",message:"Something went wrong. Please try again later.",backgroundColor:"red",messageColor:"white"})}finally{f(),r.target.reset()}}async function R(r){l++,c.disabled=!0,m();try{const t=await u(d,l);h(t.hits);const a=Math.ceil(t.totalHits/15);l>=a&&(y(),n.warning({position:"topRight",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"white"}));const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}catch(t){console.log(t.message),n.error({position:"topRight",message:"Something went wrong. Please try again later.",backgroundColor:"red",messageColor:"white"})}finally{f(),c.disabled=!1}}
//# sourceMappingURL=index.js.map
