import{a as S,S as C,i}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const P="55724103-14f076f0e5cd96e081e15651b",v="https://pixabay.com/api/";async function u(r,t){const{data:a}=await S(v,{params:{per_page:15,page:t,key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}});return a}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),c=document.querySelector(".js-load-more");let M=new C(".gallery a",{captionsData:"alt",captionDelay:200});function p(r){const t=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:n,comments:w,downloads:L})=>`
    <li class="gallery-item">
    <a href="${s}"><img src="${a}" alt="${e}" class="gallery-image"/></a>
    <ul class="gallery-item-list">
    <li><p>Likes<br> <span>${o}</span></p></li>
    <li><p>Views<br> <span>${n}</span></p></li>
    <li><p>Comments<br> <span>${w}</span></p></li>
    <li><p>Downloads<br> <span>${L}</span></p></li>
    
    </ul>
    </li>
    `).join("");g.insertAdjacentHTML("beforeend",t),M.refresh()}function q(){g.innerHTML=""}function m(){h.classList.remove("is-hidden")}function f(){h.classList.add("is-hidden")}function y(){c.classList.remove("is-hidden")}function b(){c.classList.add("is-hidden")}const R=document.querySelector(".form");R.addEventListener("submit",$);let l=1,d="";c.addEventListener("click",k);async function $(r){if(r.preventDefault(),d=r.currentTarget.elements["search-text"].value.trim(),d===""){i.warning({position:"topRight",message:"Please fill out this field.",backgroundColor:"white"});return}l=1,q(),m(),b();try{const t=await u(d,l);t.hits.length===0?i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white"}):(p(t.hits),Math.ceil(t.totalHits/15)>1?y():i.warning({position:"topRight",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"white"}))}catch(t){console.log(t),i.error({position:"topRight",message:"Something went wrong. Please try again later.",backgroundColor:"red",messageColor:"white"})}finally{f(),r.target.reset()}}async function k(r){l++,c.disabled=!0,b(),m();try{const t=await u(d,l);p(t.hits);const a=Math.ceil(t.totalHits/15);l<a?y():i.warning({position:"topRight",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"white"});const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}catch(t){console.log(t.message),i.error({position:"topRight",message:"Something went wrong. Please try again later.",backgroundColor:"red",messageColor:"white"})}finally{f(),c.disabled=!1}}
//# sourceMappingURL=index.js.map
